### ISSUE TITLE
[Config] Source Code

### ISSUE THREAD

**Issue by vitran12** [yorkie-team/yorkie-ui#36]
## **Task**

- [x] Setup StoryBook

<img width="1685" alt="Screenshot 2023-12-12 at 10 53 30" src="https://github.com/yorkie-team/yorkie-ui-poc/assets/150248298/8dd2e6fb-ab09-4be5-ae28-20de23ce8770">

- [x] Setup run app 

<img width="1683" alt="Screenshot 2023-12-11 at 17 36 49" src="https://github.com/yorkie-team/yorkie-ui-poc/assets/150248298/b49ca2e1-8879-47e8-a1df-d823b05c7654">

- [x] Setup Eslint, Prettier, Stylelint

<img width="842" alt="Screenshot 2023-12-14 at 10 56 45" src="https://github.com/yorkie-team/yorkie-ui-poc/assets/150248298/cfc91412-b6dd-4f87-9166-a2ef7797bfeb">

- [x] Add Config [Panda Css](https://panda-css.com/) + [Park UI ](https://park-ui.com/)
